### PR TITLE
Add a writer interface

### PR DESCRIPTION
**Pull request by scolsen**
This PR is similar to the recent reader interface PR, only this time around we're adding a writer interface, `write-to-file`. Just like the reader, we currently define implementations for Byte Arrays and Strings.

Updates `File.write` and the corresponding test accordingly.

### CODE REVIEW

**Review by hellerve — COMMENTED** [review]
In the cases we have here, `len` can be gathered from the structures. What was the intent of adding the argument?

**Comment by scolsen** [comment]
> In the cases we have here, `len` can be gathered from the structures. What was the intent of adding the argument?

Good point! There's no technical reason, I thought it might be more flexible for callers, but in the case in which one just wants to print some segment, that should probably be handled separately (e.g. by calling Array.suffix or slice or w/e first)

I'll change the signature to be just `(Fn [&File &a] (Result Int String))`

I guess technically it could be maximally generic too as `(Fn [&File a] (Result Int String))` -- then it's up to implementors to decide if their implementation should take ownership or not, wdyt?

**Comment by hellerve** [comment]
That sounds reasonable to me!

**Comment by scolsen** [comment]
Updated the signature

**Review by hellerve — APPROVED** [review]
Looks great, thank you for the change!

**Pull request merged**
